### PR TITLE
Bluetooth Support

### PR DESCRIPTION
**Pull request by timemaster5**

### CODE REVIEW

**Comment by kiteretro** [comment]
Merged into a feature branch for now, I need to spend a bit more time working on it and it seemed easier this way! I'll be working on this today, see how it goes! Thanks for all your hard work btw!

**Comment by piklz** [comment]
Awesome kite

**Comment by kiteretro** [comment]
Just to let you know this is still work in progress :)

**Comment by kiteretro** [comment]
If anyone is interested in trying this out, this build should work: https://mega.nz/#!iDIV1Yzb!O7LYl8IwB4h9bIjwAZGgRf38UOwDedXj7mkz5RlJ1Vc Any comments are appreciated!

**Comment by mousemat86** [comment]
took me a while to discover this branch but the Bluetooth on my circuit sword is working now. 

How can I bring it back up once rebooting to HDMI? Do I need to modify the PCB or can it be done through software?

**Pull request merged**
